# Generated by Django 5.2.4 on 2025-07-25 07:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название проекта')),
                ('description', models.TextField(verbose_name='Описание проекта')),
                ('background', models.TextField(verbose_name='Предпосылки проекта')),
                ('status', models.CharField(max_length=100, verbose_name='Статус проекта')),
                ('relevance', models.TextField(verbose_name='Актуальность')),
                ('goal', models.TextField(verbose_name='Цель проекта')),
                ('results', models.TextField(verbose_name='Результаты и продукты проекта')),
                ('team', models.JSONField(default=list, verbose_name='Роли и телефоны')),
                ('audience', models.TextField(verbose_name='Целевая аудитория')),
                ('event_type', models.CharField(max_length=200, verbose_name='Вид мероприятия')),
                ('risks', models.JSONField(default=list, verbose_name='Риски и их влияния')),
                ('material_resources', models.TextField(verbose_name='Материальные ресурсы')),
                ('non_material_resources', models.TextField(verbose_name='Нематериальные ресурсы')),
                ('metrics', models.JSONField(default=list, verbose_name='Метрики и цели')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('actual_metrics', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.project')),
            ],
        ),
    ]
