# Generated by Django 5.2.4 on 2025-07-25 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_eventphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='actual_metrics',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Фактические значения'),
        ),
    ]
